layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: enakero
  # youtube: your_username
  # vk: your_username

topics:
  - name: PHP
    web_url: https://github.com/topics/php
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/php/php.png

  - name: DevOps
    web_url: https://gist.github.com/jpswade/4135841363e72ece8086146bd7bb5d91
    image_url: https://cdn-images-1.medium.com/max/2560/1*EBXc9eJ1YRFLtkNI_djaAw.png

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://upload.wikimedia.org/wikipedia/commons/3/35/Tux.svg